name: Test Container Wait
on: workflow_dispatch
jobs:
  test:
    runs-on: Linux
    steps:
    - name: Wait for a Message
      uses: soda480/wait-for-message-action@main
      id: wait
      with:
        command: "wait"
        port: 8080
        message: "ready to proceed"
        timeout: 60
    - name: Continue
      run: echo "Continue running... response from wait was - ${{ steps.wait.outputs.response_linux }}"
