name: Test wait-for-ip Store-Linux Wait-Windows
on: workflow_dispatch
jobs:
  store:
    runs-on: Linux
    steps:
    - name: On Linux - Sleep for a bit
      run: sleep 60
    - name: On Linux - Store IP
      uses: soda480/wait-for-ip-action@main
      with:
        command: "store"
        redis_host: "192.168.1.199"
        tag: "Lin001"
  wait:
    runs-on: Windows
    steps:
    - name: On Windows - Wait Linux IP
      uses: soda480/wait-for-ip-action@main
      id: get_linux_ip
      with:
        command: "wait"
        redis_host: "192.168.1.199"
        tag: "Lin001"
        delay: 10
        attempts: 18
        shell: cmd
    - name: On Windows - Show Linux IP
      run: |
        echo "The Linux IP address is: ${{ steps.get_linux_ip.outputs.response_windows }}"
