name: Test Jobs Sync within Steps using Wait for IP
on: workflow_dispatch
jobs:

  windows_workflow:
    name: Windows Workflow
    runs-on: windows-latest
    steps:

    - name: Store Windows IP
      uses: soda480/wait-for-ip-action@main
      with:
        command: "store"
        redis_host: "db-redis-sfo2-44676-do-user-5080416-0.b.db.ondigitalocean.com"
        redis_port: 25061
        redis_password: ${{ secrets.REDIS_PASSWORD }}
        tag: "Windows1"

    - name: Wait Linux IP
      uses: soda480/wait-for-ip-action@main
      id: get_linux_ip
      with:
        command: "wait"
        redis_host: "db-redis-sfo2-44676-do-user-5080416-0.b.db.ondigitalocean.com"
        redis_port: 25061
        redis_password: ${{ secrets.REDIS_PASSWORD }}
        tag: "Linux1"
        delay: 10
        attempts: 18
        shell: cmd

    - name: Wait for Linux server to be ready
      uses: soda480/wait-for-message-action@main
      with:
        command: "wait"
        port: 8080
        timeout: 120
        message: "Linux server is ready"
        shell: cmd

    - name: Install App Task
      run: Start-Sleep -s 30
      shell: powershell

    - name: Send Windows server is ready message
      uses: soda480/wait-for-message-action@main
      with:
        command: "send"
        ip: ${{ steps.get_linux_ip.outputs.response_windows }}
        port: 8080
        delay: 5
        attempts: 12
        message: "Windows server is ready"
        shell: cmd

  linux_workflow:
    name: Linux Workflow
    runs-on: ubuntu-latest
    steps:
    
    - name: Store Linux IP
      uses: soda480/wait-for-ip-action@main
      with:
        command: "store"
        redis_host: "db-redis-sfo2-44676-do-user-5080416-0.b.db.ondigitalocean.com"
        redis_port: 25061
        redis_password: ${{ secrets.REDIS_PASSWORD }}
        tag: "Linux1"
        use_container: true
    
    - name: Wait Windows IP
      uses: soda480/wait-for-ip-action@main
      id: wait
      with:
        command: "get_windows_ip"
        redis_host: "db-redis-sfo2-44676-do-user-5080416-0.b.db.ondigitalocean.com"
        redis_port: 25061
        redis_password: ${{ secrets.REDIS_PASSWORD }}
        tag: "Windows1"
        delay: 10
        attempts: 18
        use_container: true
    
    - name: Build App Task
      run: sleep 60
      shell: bash
  
    - name: Send Linux server is ready message
      uses: soda480/wait-for-message-action@main
      with:
        command: "send"
        ip: ${{ steps.get_windows_ip.outputs.response_container }}
        port: 8080
        delay: 10
        attempts: 10
        message: "Linux server is ready"
        shell: bash
        use_container: true
  
    - name: Wait for Windows server to be ready message
      uses: soda480/wait-for-message-action@main
      with:
        command: "wait"
        port: 8080
        timeout: 120
        message: "Windows server is ready"
        shell: bash
        use_container: true
  
    - name: Run Tests Task
      run: sleep 10
      shell: bash
